<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE ArrayOfTemplateBind [
	<!ELEMENT ArrayOfTemplateBind (TemplateBind*)>
	<!ELEMENT TemplateBind (#PCDATA)>
	<!ATTLIST TemplateBind typeID CDATA #REQUIRED>
	<!ATTLIST TemplateBind systemID CDATA #IMPLIED>
	<!ATTLIST TemplateBind remote (True|False) #IMPLIED>
]>
<!--
Root: D:\Users\shot\source\repos\DocumentAggregator\Templates\Edited\
-->
<ArrayOfTemplateBind xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<TemplateBind typeID="2267905">БПД/Заявка на доступ удаленных сотрудников к ИС.DOCX</TemplateBind>
	<!-- Placeholder : Currently working on the document below : Not formatted well -->
	<TemplateBind typeID="10" systemID="1" remote="False">КРР-01 ИС УЛК/Заявка для сотрудников НТЦ УЛК.docx</TemplateBind> <!-- Integraph SmartPlant & CADWorx -->
	<TemplateBind typeID="10" systemID="1" remote="True">КРР-01 ИС УЛК/Заявка для удаленных сотрудников НТЦ УЛК.docx</TemplateBind> <!-- Integraph SmartPlant & CADWorx -->
	<TemplateBind typeID="10" systemID="3" remote="False">КРР-03 ИС КП/Заявка для сотрудников НТЦ ИС КП.DOCX</TemplateBind>
	<TemplateBind typeID="10" systemID="3" remote="True">КРР-03 ИС КП/Заявка для удаленных сотрудников НТЦ.docx</TemplateBind>
	<TemplateBind typeID="10" systemID="4" remote="False">КРР-04 ИС ОДФР/Заявка для сотрудников НТЦ.docx</TemplateBind>
	<TemplateBind typeID="10" systemID="4" remote="True">КРР-04 ИС ОДФР/Заявка для удаленных сотрудников НТЦ.docx</TemplateBind>
	<TemplateBind typeID="10" systemID="5" ><!-->remote="False"><!-->КРР-05 ИС ОИСД/Заявка для сотрудников НТЦ ИС ОИСД.docx</TemplateBind> <!-- Don't process -->
	<TemplateBind typeID="10" systemID="8" ><!-->remote="True"><!-->КРР-08 ИС 1С БУНУ/Заявка для сотрудников НТЦ.docx</TemplateBind>
	<!--TemplateBind typeID="-1" systemID="8">КРР-08 ИС 1С Заявка для сотрудников РН-Учет (Версия 2.3.0).docx</TemplateBind--> <!-- For РН-Учёт -->
	<TemplateBind typeID="10" systemID="10" ><!-->remote="True"><!-->КРР-10 ИС АСЭР/Заявка для удаленных сотрудников НТЦ.docx</TemplateBind>
	<!--TemplateBind typeID="10" systemID="11" remote="True">КРР-11 ИС ТД/Заявка для сотрудников НТЦ (версия 2.0.5).docx</TemplateBind--> <!-- Also check the PC/ARM name --> <!-- Check the last frames correctness -->
	<TemplateBind typeID="10" systemID="11">КРР-11 ИС ТД/Заявка для сотрудников НТЦ.docx</TemplateBind>
	<TemplateBind typeID="-1" systemID="11">КРР-11 ИС ТД/Заявка для сотрудников ОГ_ДО (Версия 2.1.0).docx</TemplateBind> <!-- Check an organization name -->
	<TemplateBind typeID="10" systemID="14">КРР-14 ИС УДФР/Заявка для сотрудников НТЦ УДФР.docx</TemplateBind> <!-- The denied role is missing -->
	<TemplateBind typeID="-1" systemID="14">КРР-14 ИС УДФР/Заявка для сотрудников ОГ_ДО УДФР.docx</TemplateBind> <!-- The denied role is missing -->
	<TemplateBind typeID="10" systemID="15">КРР-15 ИС КНИ/Заявка для сотрудников НТЦ КНИ.docx</TemplateBind> <!-- Don't process -->
	<TemplateBind typeID="10" systemID="17" remote="True">КРР-17 ИС ОиК/Заявка для удаленных сотрудников НТЦ.docx</TemplateBind>
	<TemplateBind typeID="10" systemID="17" remote="False">КРР-17 ИС ОиК/Заявка для сотрудников НТЦ (ИС ОиК, офис).docx</TemplateBind>
	<TemplateBind typeID="10" systemID="18" remote="True">КРР-18 ИС СЭД/Заявка для удаленных сотрудников НТЦ.docx</TemplateBind> <!-- Check access right "КП: Протоколы" -->
	<TemplateBind typeID="10" systemID="18" remote="False">КРР-18 ИС СЭД/Заявка для сотрудников НТЦ (ИС СЭД, офис).docx</TemplateBind> <!-- Check access right "КП: Протоколы" -->
	<TemplateBind typeID="10" systemID="19" ><!-->remote="True"><!-->КРР-19 ИС РН-КИН/Заявка для удаленных сотрудников НТЦ.docx</TemplateBind>
	<TemplateBind typeID="10" systemID="20" ><!-->remote="True"><!-->КРР-20 ИС СУПП/Заявка для сотрудников НТЦ.docx</TemplateBind>
	<TemplateBind typeID="10" systemID="21" ><!-->remote="True"><!-->КРР-21 ИС WDB/Заявка для удаленных сотрудников НТЦ.docx</TemplateBind>
	<TemplateBind typeID="10" systemID="24" remote="False">КРР-24 ИС ЛУ ЦГИС/Заявка для сотрудников НТЦ ИС ЛУ ЦГИС.DOCX</TemplateBind>
	<TemplateBind typeID="10" systemID="24" remote="True">КРР-24 ИС ЛУ ЦГИС/Заявка для удаленных сотрудников НТЦ.docx</TemplateBind>
	<TemplateBind typeID="10" systemID="25" ><!-->remote="True"><!-->КРР-25 ИС АБПО/Заявка для сотрудников НТЦ.docx</TemplateBind> <!-- Single informational resource -->
	<TemplateBind typeID="10" systemID="31">КРР-31 ИС РДРИ/Заявка для сотрудников НТЦ РДРИ.docx</TemplateBind> <!-- EXPIRE field -->
	<TemplateBind typeID="10" systemID="34" ><!-->remote="True"><!-->КРР-34 ИС NormaCS/Заявка для удаленных сотрудников НТЦ.docx</TemplateBind>
	<TemplateBind typeID="10" systemID="35" ><!-->remote="True"><!-->КРР-35 ИС ПП/Заявка для удаленных сотрудников НТЦ.docx</TemplateBind>
	<TemplateBind typeID="10" systemID="37" ><!-->remote="True"><!-->КРР-37 ИС ВОТ/Заявка для удаленных сотрудников НТЦ.docx</TemplateBind>
	<TemplateBind typeID="10" systemID="38" ><!-->remote="True"><!-->КРР-38 ИС Геобанк-ПТД/Заявка для удаленных сотрудников НТЦ.docx</TemplateBind>
	<TemplateBind typeID="10" systemID="39" remote="False">КРР-39 ИС ПР/Заявка для сотрудников НТЦ.DOCX</TemplateBind>
	<TemplateBind typeID="10" systemID="39" remote="True">КРР-39 ИС ПР/Заявка для удаленных сотрудников НТЦ.docx</TemplateBind>
	<TemplateBind typeID="10" systemID="41" ><!-->remote="True"><!-->КРР-41 ИС СУРК/Заявка для удаленных сотрудников НТЦ.docx</TemplateBind>
	<TemplateBind typeID="10" systemID="42" remote="True">КРР-42 ИС Вектор/Заявка для удаленных сотрудников НТЦ ИС Вектор.docx</TemplateBind>
	<TemplateBind typeID="10" systemID="42" remote="False">КРР-42 ИС Вектор/Заявка для сотрудников НТЦ (ИС Вектор, офис).docx</TemplateBind>
	<TemplateBind typeID="10" systemID="44" ><!-->remote="True"><!-->КРР-44 ИС УСИЗ/Заявка для удаленных сотрудников НТЦ.docx</TemplateBind>
	<TemplateBind typeID="10" systemID="45" ><!-->remote="True"><!-->КРР-45 ИС КУЗ/Заявка для удаленных сотрудников НТЦ.docx</TemplateBind>
	<TemplateBind typeID="10" systemID="46" remote="True">КРР-46 ИС СУТ/Заявка на доступ к системе СУТЗ (для удаленных сотрудников).docx</TemplateBind> <!-- Too much roles just don't exist -->
	<TemplateBind typeID="10" systemID="46" remote="False">КРР-46 ИС СУТ/Заявка на доступ к системе СУТЗ.docx</TemplateBind> <!-- Too much roles just don't exist -->
	<TemplateBind typeID="10" systemID="47" remote="False">КРР-47 ИС Сапсан+/Заявка для сотрудников НТЦ Сапсан+.docx</TemplateBind>
	<TemplateBind typeID="10" systemID="47" remote="True">КРР-47 ИС Сапсан+/Заявка для удаленных сотрудников НТЦ Сапсан+.docx</TemplateBind>
	<TemplateBind typeID="10" systemID="53">КРР-53 ИС ХКД/Заявка на доступ пользователей в ИС ХКД.docx</TemplateBind>
	<TemplateBind typeID="10" systemID="57" remote="False">КРР-57 ИС КП 2.0/Заявка для сотрудников НТЦ ИС КП 2.0.docx</TemplateBind> <!-- Owner role -->
	<TemplateBind typeID="10" systemID="57" remote="True">КРР-57 ИС КП 2.0/Заявка для удаленных сотрудников ИС КП2.0.docx</TemplateBind> <!-- Owner role -->
	<TemplateBind typeID="10" systemID="101" ><!-->remote="True"><!-->КРР-101 ИС КонсультантПлюс/Заявка для сотрудников НТЦ КОНСУЛЬТАНТПЛЮС.docx</TemplateBind> <!-- In work -->
</ArrayOfTemplateBind>
