<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE ArrayOfSqlQuery [
	<!ELEMENT ArrayOfSqlQuery (SqlQuery*)>
	<!ELEMENT SqlQuery (#PCDATA)>
	<!ATTLIST SqlQuery name CDATA #REQUIRED>
	<!ATTLIST SqlQuery obsolete CDATA #IMPLIED>
]>
<!--
P - procedures, end with ';'
Q - queries, end without ';'
-->
<ArrayOfSqlQuery xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<SqlQuery name="P_SQLErrorIndexRetrieve">
DECLARE
	c        INTEGER := DBMS_SQL.open_cursor();
	errorpos integer := -1;
BEGIN
	BEGIN
		DBMS_SQL.parse(c, :sqltext, DBMS_SQL.native);
	EXCEPTION
		WHEN OTHERS THEN
			errorpos := DBMS_SQL.LAST_ERROR_POSITION();
	END;
	:errorpos := errorpos;
	DBMS_SQL.close_cursor(c);
END;
	</SqlQuery>
	<SqlQuery name="Q_HRDCategoryAttributeNames_ByRequest">
select
	cat.request_attr_name as category,
	attr.request_attr_name as attribute
from hrd.request_attr_hdr attr
	join hrd.request_attr_hdr cat
		on (attr.p_request_attr_hdr_id = cat.request_attr_hdr_id)
	join hrd.request_attr_types typ
		on (attr.request_attr_hdr_id = typ.request_attr_hdr_id)
	join hrd.request_hdr req
		on (req.request_type_id = typ.request_type_id)
where req.request_hdr_id = {0}
order by typ.order_number
	</SqlQuery>
	<SqlQuery name="Q_HRDAttributeIdsValues_ByRequest">
select
	attr.request_attr_hdr_id AS attr_id,
    pty.value_number
		|| pty.value_varchar2
        || pty.value_date
        || decode(pty.value_boolean, 0, 'Нет', 1, 'Да', null)
        || pty.value_clob
		AS attr_value
from hrd.request_attr_hdr attr
    join hrd.request_attr_hdr cat
        on (attr.p_request_attr_hdr_id = cat.request_attr_hdr_id)
    join hrd.request_attr_types typ
        on (attr.request_attr_hdr_id = typ.request_attr_hdr_id)
    join hrd.request_hdr req
        on (req.request_type_id = typ.request_type_id)
    -- Позволяет выбирать атрибуты заявки из hrd.request_attr_hdr
    -- без какого-либо значения из hrd.request_attr_pty
    left outer join hrd.request_attr_pty pty
        on (pty.request_attr_hdr_id = attr.request_attr_hdr_id
            AND pty.request_hdr_id = req.request_hdr_id)
where req.request_hdr_id = {0}
order by typ.order_number
	</SqlQuery>
	<SqlQuery name="Q_HRDAddressAction_ByRequest">
SELECT
    pkzi.pkzi_name AS pkzi,
    build.description AS address,
    CASE MAX(acc.action)
        WHEN 0 THEN 'False'
        ELSE 'True'
    END AS allow,
    CASE
        WHEN MAX(acc.action) = MIN(acc.action) THEN 'False'
        ELSE 'True'
    END AS change,
    CASE MIN(acc.action)
        WHEN 0 THEN 'True'
        ELSE 'False'
    END AS deny
FROM hrd.request_hdr req
    JOIN hrd.register_pkzi pkzi ON (pkzi.user_id = req.applicant_id)
    JOIN obd_sys.user_location loc ON (loc.user_id = req.applicant_id)
    JOIN hrd.dict_room room ON (room.room_id = loc.room_id)
    JOIN hrd.building build ON (build.building_id = room.building_id)
    JOIN hrd.it_access_right_request acc ON (acc.request_hdr_id = req.request_hdr_id)
WHERE req.request_hdr_id = {0}
GROUP BY pkzi.pkzi_name, build.description
	</SqlQuery>
	<SqlQuery name="Q_HRDClaimSystemID_ByRequest">
select distinct req.request_type_id req_type, sys.register_id inf_sys
from hrd.request_hdr req
    JOIN hrd.it_access_right_request acc ON (acc.request_hdr_id = req.request_hdr_id)
    JOIN hrd.it_access_right_hdr rit ON (rit.access_right_hdr_id = acc.access_right_hdr_id)
    JOIN hrd.it_dict_information_resource res ON (res.information_resource_id = rit.object_id)
    JOIN hrd.it_dict_information_system sys ON (sys.information_system_id = res.information_system_id)
where req.request_hdr_id = {0}
	</SqlQuery>
	<SqlQuery name="Q_HRDClaimFieldsList_ByRequest">
select
    cat.request_attr_name as category,
    attr.request_attr_name as attribute,
    attr.request_attr_hdr_id AS attr_id,
    pty.value_number
        || pty.value_varchar2
        || pty.value_date
        || decode(pty.value_boolean, 0, 'Нет', 1, 'Да', null)
        || pty.value_clob
        AS attr_value
from hrd.request_attr_hdr attr
    join hrd.request_attr_hdr cat
        on (attr.p_request_attr_hdr_id = cat.request_attr_hdr_id)
    join hrd.request_attr_types typ
        on (attr.request_attr_hdr_id = typ.request_attr_hdr_id)
    join hrd.request_hdr req
        on (req.request_type_id = typ.request_type_id)
    -- Позволяет выбирать атрибуты заявки из hrd.request_attr_hdr
    -- без какого-либо значения из hrd.request_attr_pty
    left outer join hrd.request_attr_pty pty
        on (pty.request_attr_hdr_id = attr.request_attr_hdr_id
            AND pty.request_hdr_id = req.request_hdr_id)
where req.request_hdr_id = {0}
order by typ.order_number
    </SqlQuery>
	<SqlQuery name="Q_HRDClaimAccessList_ByRequest">
select
    rit.name,
    rit.access_right_hdr_id as code,
    acc.action
from (
    select
       rit.name,
       rit.access_right_hdr_id
    from hrd.it_access_right_hdr rit
    where rit.object_id = (
        select distinct
           res.information_resource_id
        from hrd.it_dict_information_resource res
            JOIN hrd.it_access_right_hdr rit ON (rit.object_id = res.information_resource_id)
            JOIN hrd.it_access_right_request acc ON (acc.access_right_hdr_id = rit.access_right_hdr_id)
            JOIN hrd.request_hdr req ON (req.request_hdr_id = acc.request_hdr_id)
        where 
            req.request_hdr_id = {0}
    ) and rit.request_available = 1
) rit full outer join (
    select
       acc.action,
       acc.access_right_hdr_id
    from hrd.it_access_right_hdr rit
        JOIN hrd.it_dict_information_resource res ON (res.information_resource_id = rit.object_id)
        JOIN hrd.it_access_right_request acc ON (acc.access_right_hdr_id = rit.access_right_hdr_id)
        JOIN hrd.request_hdr req ON (req.request_hdr_id = acc.request_hdr_id)
    where 
        req.request_hdr_id = {0}
) acc on (rit.access_right_hdr_id = acc.access_right_hdr_id)
order by rit.access_right_hdr_id
	</SqlQuery>
	<SqlQuery name="Q_HRDClaimFieldNameList_ByRequestType">
select
    cat.request_attr_name as category,
    attr.request_attr_name as attribute,
    attr.request_attr_hdr_id AS attr_id
from hrd.request_attr_hdr attr
    join hrd.request_attr_hdr cat
        on (attr.p_request_attr_hdr_id = cat.request_attr_hdr_id)
    join hrd.request_attr_types typ
        on (attr.request_attr_hdr_id = typ.request_attr_hdr_id)
where typ.request_type_id = {0}
order by typ.order_number
    </SqlQuery>
	<SqlQuery name="Q_HRDClaimInformationalResourcesList_ByRequest">
select
    rit.res_name,
    rit.res_id,
    rit.name,
    rit.access_right_hdr_id as code,
    acc.action
from (
    select
       res.name as res_name,
       res.information_resource_id as res_id,
       rit.name,
       rit.access_right_hdr_id
    from hrd.it_access_right_hdr rit
        join hrd.it_dict_information_resource res ON (res.information_resource_id = rit.object_id)
    where rit.object_id in (
        select distinct
           res.information_resource_id
        from hrd.it_dict_information_resource res
            JOIN hrd.it_access_right_hdr rit ON (rit.object_id = res.information_resource_id)
            JOIN hrd.it_access_right_request acc ON (acc.access_right_hdr_id = rit.access_right_hdr_id)
            JOIN hrd.request_hdr req ON (req.request_hdr_id = acc.request_hdr_id)
        where 
            req.request_hdr_id = {0}
    ) and rit.request_available = 1
) rit full outer join (
    select
       acc.action,
       acc.access_right_hdr_id
    from hrd.it_access_right_hdr rit
        JOIN hrd.it_dict_information_resource res ON (res.information_resource_id = rit.object_id)
        JOIN hrd.it_access_right_request acc ON (acc.access_right_hdr_id = rit.access_right_hdr_id)
        JOIN hrd.request_hdr req ON (req.request_hdr_id = acc.request_hdr_id)
    where 
        req.request_hdr_id = {0}
) acc on (rit.access_right_hdr_id = acc.access_right_hdr_id)
order by rit.access_right_hdr_id
    </SqlQuery>
</ArrayOfSqlQuery>
